import { useState } from 'react'
import { openAtlasSource } from '../../utils/atlasHost'
import { ArrowDownLeft, ArrowUpRight, BookOpen, ChevronRight, ExternalLink, X } from 'lucide-react'
import { ancestorsOf, safeSourceUrl } from '../../utils/atlasGraph'

function Sources({ sources = [], onOpenSource }) {
  const [openError, setOpenError] = useState('')
  const open = async (event, url) => {
    setOpenError('')
    try { await openAtlasSource(event, url, onOpenSource) } catch { setOpenError('Unable to open this source. Please try again.') }
  }
  const links = sources.map(source => ({ ...source, href: safeSourceUrl(source.url) })).filter(source => source.href)
  return <div className="atlas-inspector-section"><h3><BookOpen size={14} /> Evidence & documentation</h3>{links.length ? <ul className="atlas-source-list">{links.map((source, order) => <li key={`${source.href}-${order}`}><a href={source.href} onClick={event => open(event, source.href)} target="_blank" rel="noopener noreferrer"><span>{source.label || source.type || 'Source'}{source.revision && <small>Revision {String(source.revision).slice(0, 12)}</small>}</span><ExternalLink size={14} /></a></li>)}</ul> : <p className="atlas-muted">No source link recorded for this item.</p>}{openError && <p role="alert">{openError}</p>}</div>
}

export default function AtlasInspector({ node, relationship, model, index, expanded, onSelect, onFocus, onOpenSource, onToggle, onClose }) {
  if (relationship) {
    return <aside className="atlas-inspector" aria-label="Relationship details"><div className="atlas-inspector-heading"><span className="atlas-kicker">Relationship</span><button onClick={onClose} aria-label="Close relationship details"><X size={18} /></button></div><h2>{relationship.kind.replaceAll('_', ' ')}</h2><p className="atlas-relationship-path">{index.byId.get(relationship.source)?.label}<ArrowUpRight size={18} />{index.byId.get(relationship.target)?.label}</p><p>{relationship.members.length} documented relationship{relationship.members.length === 1 ? '' : 's'} represented by this line. Direction and type are preserved when nodes collapse.</p><div className="atlas-inspector-section"><h3>Underlying connections</h3>{relationship.members.map(edge => <div key={edge.id} className="atlas-underlying-edge"><strong>{edge.label || edge.kind}</strong><span>{index.byId.get(edge.source)?.label} → {index.byId.get(edge.target)?.label}</span><span className="atlas-status">{edge.status || 'documented'}</span></div>)}</div><Sources sources={relationship.members.flatMap(edge => edge.sources || [])} onOpenSource={onOpenSource} /></aside>
  }
if (!node) return <aside className="atlas-inspector atlas-inspector--intro" aria-label="About this map"><span className="atlas-kicker">One system, many scales</span><h2>A map you can open.</h2><p>Start with a domain. Expand only what you need; the rest of the system stays in context.</p><ol className="atlas-instructions"><li><span>01</span><div><strong>Explore the structure</strong><p>Use the arrow on a node to reveal what is inside.</p></div></li><li><span>02</span><div><strong>Follow a process</strong><p>Choose a journey to trace interactions, one step at a time.</p></div></li><li><span>03</span><div><strong>Inspect the evidence</strong><p>Select a node or connection for its sources and documentation.</p></div></li></ol><div className="atlas-truth-note"><strong>Architecture, not telemetry</strong><p>This is a versioned documentation snapshot. Presence on this map does not imply a component is deployed or healthy.</p></div><div className="atlas-inspector-section"><h3>Snapshot coverage</h3><p>{model.coverage?.summary || model.coverage?.scope || model.description}</p>{Array.isArray(model.coverage?.limitations) && <ul className="atlas-limitations">{model.coverage.limitations.map(item => <li key={item}>{item}</li>)}</ul>}</div></aside>
  const children = index.children.get(node.id) || []
  const connections = model.edges.filter(edge => edge.source === node.id || edge.target === node.id)
  const path = ancestorsOf(index, node.id).map(nodeId => index.byId.get(nodeId))
  return <aside className="atlas-inspector" aria-label={`${node.label} details`}><div className="atlas-inspector-heading"><span className="atlas-kicker">{node.kind.replaceAll('_', ' ')}</span><button onClick={onClose} aria-label="Close component details"><X size={18} /></button></div><nav className="atlas-breadcrumb" aria-label="Component hierarchy">{path.filter(parent => parent.id !== index.root.id).map(parent => <button key={parent.id} onClick={() => onSelect(parent.id)}>{parent.label}<ChevronRight size={12} /></button>)}</nav><h2>{node.label}</h2><button className="atlas-button atlas-zen-focus" onClick={() => onFocus(node.id)}>Focus in Zen</button><span className={`atlas-status atlas-status--${node.status}`}>{node.status || 'documented'}</span><p>{node.description || 'No description recorded.'}</p>{children.length > 0 && <div className="atlas-inspector-section"><div className="atlas-section-heading"><h3>Inside · {children.length}</h3><button onClick={() => onToggle(node.id)}>{expanded.has(node.id) ? 'Collapse' : 'Expand'}</button></div><ul className="atlas-child-list">{children.map(child => <li key={child.id}><button onClick={() => onSelect(child.id)}><span>{child.label}<small>{child.kind.replaceAll('_', ' ')}</small></span><ChevronRight size={15} /></button></li>)}</ul></div>}<div className="atlas-inspector-section"><h3>Direct connections · {connections.length}</h3>{connections.length ? <ul className="atlas-child-list">{connections.map(edge => { const outgoing = edge.source === node.id; const other = index.byId.get(outgoing ? edge.target : edge.source); return <li key={edge.id}><button onClick={() => onSelect(other.id)}>{outgoing ? <ArrowUpRight size={15} /> : <ArrowDownLeft size={15} />}<span>{other.label}<small>{edge.label || edge.kind}</small></span></button></li> })}</ul> : <p className="atlas-muted">No direct connections recorded at this level. Expand to inspect internal components.</p>}</div><Sources sources={node.sources} onOpenSource={onOpenSource} /><p className="atlas-item-id">{node.id}</p></aside>
}
